import { Note } from '../../models/notes.model';

export const expectedNotesState: Note[] = [
  {
    _id: ' 123',
    date: new Date(9, 11, 24),
    company: '77 Software Ltd',
    project: 'A Project',
    technology: 'Angular',
    title: 'array - insert at beginning with unshift',
    detail: `unshift adds to the start of the array as opposed to push which adds to the end', profile.education.unshift(newEducation)`,
    createdBy: 'simon',
    subjectArea: 'javascript',
    course: 'javascript',
    courseSection: 'javascript section',
    gitRepo: 'jkjkjkjlj',
    gitCommit: 'a comm',
    htmlContent: 'hkjhkjhkjkh',
    content: ' a test content',
    time: new Date(),
    user: { name: 'simon' },
  },
];
export const expectedNotesStateMultiple: Note[] = [
  {
    _id: ' 123',
    date: new Date(9, 11, 24),
    company: '77 Software Ltd',
    project: 'A Project',
    technology: 'Angular',
    title: 'array - insert at beginning with unshift',
    detail: `unshift adds to the start of the array as opposed to push which adds to the end', profile.education.unshift(newEducation)`,
    createdBy: 'simon',
    subjectArea: 'javascript',
    course: 'javascript',
    courseSection: 'javascript section',
    gitRepo: 'jkjkjkjlj',
    gitCommit: 'a comm',
    htmlContent: 'hkjhkjhkjkh',
    content: ' a test content',
    time: new Date(),
    user: { name: 'simon' },
  },
  {
    _id: ' 456',
    date: new Date(9, 11, 24),
    company: '77 Software Ltd',
    project: 'A Project',
    technology: 'Angular',
    title: 'array - insert at beginning with unshift',
    detail: `unshift adds to the start of the array as opposed to push which adds to the end', profile.education.unshift(newEducation)`,
    createdBy: 'simon',
    subjectArea: 'javascript',
    course: 'javascript',
    courseSection: 'javascript section',
    gitRepo: 'jkjkjkjlj',
    gitCommit: 'a comm',
    htmlContent: 'hkjhkjhkjkh',
    content: ' a test content',
    time: new Date(),
    user: { name: 'simon' },
  },
];
